# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: vault-secrets-plugin-tailscale

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.22'
          check-latest: true
      - run: go test ./... -timeout 2m

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions-setup@v1.0.13
      - run: earthly --ci +build
